### PR TITLE
working on a new layout

### PR DESCRIPTION
**Pull request by activescott**
**Please don't pull this yet until all todos below are resolved.**

I'm sending this PR now to get feedback on the approach and to keep my status public.

-----

This gets rid of a lot of the specific height settings that made the layout difficult to work with. Benefits are:
- More robust layout in general with less jumping around and odd behavior on specific browsers (like the intermittent #102)
- Responsive layout on narrow/mobile devices (now it renders each widget box on a screen at a time even on very small devices)
- Divides the rows of widgets into equal parts to reduce jagged "lines" in the layout

# TODO:
- [x] Font sizes somehow got bigger for some reason (trades, orderbook, volume)
- [x] New Order content is too wide, causing scrollbars
- [x] I believe there are a lot of style classes not used anywhere anymore. Remove them from black.css

### CODE REVIEW

**Comment by activescott** [comment]
@freeatnet @JonathonDunford Would be great to get some eyes on this. I think this looks better and is more robust use of css/bootstrap layout than the prior. Should be easier to maintain going forward and better mobile/responsive support with less css.

If you guys can play with it on some different browses and devices and agree it is better pull it. If you'd like some changes make them or point me to them and I can investigate.

**Comment by freeatnet** [comment]
Definitely looks more even 👍 

Some things I've noticed:
1. Extra paddings below, above, or on the sides of element (order book, ticker, trades)
2. Minor alignment issues (in Chrome, inputs vs buttons in "balances" pane)
3. Text cut off in "balances" pane on smaller screen (e.g., Chrome's "Laptop with MDPI screen" responsive setting).
4. The order in which pane widths are sacrificed on smaller screen: perhaps, we can cut the width of the trades column before we cut the width of ticker & balances.

Looking forward to more! :)

**Comment by bricedurand** [comment]
It's much clearer! 
However it might need clearer separations between sections. For exemple between Balance and Order Book sections, there isn't any space anymore. Before there was about 2px space, which makes it a bit more breathable.

Also the price chart section is smaller than on master

**Comment by activescott** [comment]
@freeatnet Thanks for the feedback. Each addressed below:

> 1. Extra paddings below, above, or on the sides of element (order book, ticker, trades)
I did this deliberately as I thought it looked clearer. Actually to @bricedurand 's point, I was trying to make the separation between sections clearer. Happy to reduce or remove padding.

> 2. Minor alignment issues (in Chrome, inputs vs buttons in "balances" pane)
This exists in the old layout too, but I've pushed a fix :)

> 3. Text cut off in "balances" pane on smaller screen (e.g., Chrome's "Laptop with MDPI screen" responsive setting).
Good catch. There seems to be some resolutions that this column didn't fit into right on the edge of bootstrap's grid before bootstrap wraps the columns (to give the widget full screen width). I pushed a fix to set it up to scroll as needed and shrank the content as down as much as I could (without redoing the react code).

> 4. The order in which pane widths are sacrificed on smaller screen: perhaps, we can cut the width of the trades column before we cut the width of ticker & balances.
I like this idea too, but I investigated and I don't see a clean way to get bootstrap to prioritize which column widths are sacrificed. I found a hack on stackoverflow but couldn't get it to work reliably myself (and it isn't supported by bootstrap officially so felt fragile).

Let me know what else you think needs done after your review.

**Comment by activescott** [comment]
@bricedurand Good one. I agree a subtle border between columns looks nice. So I've put that back in. Thanks for the feedback! Please check the latest and let us know if you think this is good to merge.

**Comment by bricedurand** [comment]
Looks good to me!

**Comment by activescott** [comment]
@forkdelta/frontend-team I've merged the latest from master. I'd like to get this merged. If there is something holding it up please let me know!

**Comment by freeatnet** [comment]
@activescott I'm still getting weird paddings and cut-off content :(

**Comment by activescott** [comment]
@freeatnet Thanks for providing feedback. Definitely don't want this to make things worse! Here is what I'm seeing in FF and Chrome on mac. Can you please point out what you're referring to in these screenshots or or give me a bit more detail if you're seeing something that I'm not seeing here.
screen shot 2018-03-18 at 4 14 00 pm

**Comment by JonathonDunford** [comment]
@activescott 

**Issue 1:**

Check out this screenshot.
I am on a 1920x1080 monitor.
The table for balances/deposits/etc. need to be full width.

https://imgur.com/a/JDKWi

**Issue 2:**

Some of the scroll bars aren't styled. Check in Chrome.

Check this screenshot: https://imgur.com/a/ej6fV

**Issue 3:**

On Mobile, the same problem as Issue 1 happens.

ALSO, the bottom of the "Make sure XXX" text gets cut off and the whole block becomes scrollable. Can we make it all in view without having to scroll the separate section?

**Issue 4:**

The order section cuts off for me on mobile as well. 

I fixed these issues on our live CSS by setting minimum widths on mobile.

**Pull request closed without merging**
